### ISSUE TITLE
サジェスト機能を軽量化

### ISSUE THREAD

**Issue by Ziphil** [Ziphil/NagiliDictionary#5]
サジェスト用の検索に1.5秒ほどかかるようなので軽量化する。

**Comment by na2co3-ftw** [comment]
参考までに、幻日辞典ではサジェストのために品詞別に見出し語だけリストアップしたファイルを作成しています。
例(動詞): http://mindsc.ape.jp/klel/yuoeda.txt

**Comment by Ziphil** [comment]
なるほど、ありがとうございます。
